=== Tr4Kar/XML/Learn1/VD2.2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Tvschedule (Channel+)>
<!ELEMENT Channel (Banner, Day+)>
<!ELEMENT Banner (#PCDATA)>
<!ELEMENT Day (Date, (Holiday | Programslot+)+)>
<!ELEMENT Holiday (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Programslot (Time, Title, Description?)>
<!ELEMENT Time (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

<!ATTLIST Tvschedule Name CDATA #REQUIRED>
<!ATTLIST Channel Chan CDATA #REQUIRED>
<!ATTLIST Programslot Vturn CDATA #IMPLIED>
<!ATTLIST Title Rating CDATA #IMPLIED>
<!ATTLIST Title Language CDATA #IMPLIED>

=== Tr4Kar/XML/Learn1/VD2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tvschedule SYSTEM "VD2.2.dtd">
<Tvschedule Name="Truyền Hình Huế">
    <Channel Chan="Huế">
        <Banner>Câu chuyện thường ngày</Banner>
        <Day>
            <Date>15/6</Date>
            <Holiday>18/6</Holiday>
            <Programslot Vturn="1">
                <Time>7:15:39</Time>
                <Title Rating="0.1" Language="Vietnamese">Khởi động 1 ngày mới</Title>
                <Description>Một ngày mới bắt đầu và tôi tự hỏi mình đã ăn sáng chưa ?</Description>
            </Programslot>
        </Day>
    </Channel>
</Tvschedule>
